version: 2

models:
  - name: silver_transactions
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - transaction_date
              - dsc
              - debit_brl
          config:
            severity: warn
    columns:
      - name: transaction_date
        tests:
          - not_null:
              config:
                severity: warn
      - name: month_key
        tests:
          - not_null:
              config:
                severity: warn
      - name: cost_center
        tests:
          - not_null:
              config:
                severity: warn
          - accepted_values:
              arguments:
                values: ['Producao', 'RH', 'Marketing', 'Fixas', 'Receita', 'Outro']
      - name: is_incoming
        tests:
          - not_null

  - name: silver_budget
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - month_key
              - cost_center
    columns:
      - name: month_key
        tests:
          - not_null
      - name: cost_center
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['Fixas', 'Impostos', 'Logistica', 'Manutencao', 'Marketing', 'Materia_Prima', 'Producao', 'RH']
      - name: budget_amount_brl
        tests:
          - not_null

  - name: silver_equipment
    columns:
      - name: item_id
        tests:
          - not_null
          - unique
      - name: machine_type
        tests:
          - not_null
      - name: production_line
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['trufa', 'pao_de_mel', 'both']
      - name: brand
      - name: model
      - name: country_of_origin
      - name: _ingested_at