version: 2

sources:
  - name: bronze
    dataset: factory_lakehouse
    tables:
      - name: bronze_transactions
      - name: bronze_budget
      - name: bronze_equipment
      - name: bronze_production_plan
      - name: bronze_maintenance_logs
      - name: bronze_r_produto
      - name: bronze_synthetic_sales